name: SonarCloud Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupération du code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Indispensable pour l'analyse Sonar

      # 2. Installation de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # On installe les bibliothèques utilisées dans vos imports
          pip install pytest pytest-cov pandas plotly streamlit selenium webdriver-manager psycopg2-binary
          
      # 4. Lancement des Tests Unitaires (Pour avoir le % de couverture)
      - name: Run Unit Tests
        # On lance les tests et on génère le rapport XML pour Sonar
        run: pytest test_unitaire.py --cov=. --cov-report=xml
      
      # 5. Lancement du Scan SonarCloud (CORRIGÉ AVEC LE SHA)
      - name: SonarCloud Scan
        # Remplacement de @v4 par le SHA spécifique pour garantir la sécurité
        uses: SonarSource/sonarqube-scan-action@5f1616cc141113c5a741639d6b7b809062363197
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}